name: Go Coverage Badge
description: Generate coverage badge for go projects
author: tj-actions
inputs:
  filename:
    description: 'File containing the tests output'
    required: true
    default: coverage.out
  color:
    description: 'Color of the badge - green/yellow/red'
    required: false
  green:
    description: 'At what percentage does the badge become green instead of yellow (default: 70)'
    required: false
  target:
    description: 'Target file (default "README.md")'
    required: false
  text:
    description: 'Text on the left side of the badge (default: "Coverage")'
    required: false
  value:
    description: 'Text on the right side of the badge'
    required: false
  yellow:
    description: 'At what percentage does the badge become yellow instead of red (default 30)'
    required: false
  link:
    description: 'Optional URL when you click the badge'
    required: false

runs:
  using: 'composite'
  steps:
    - run: |
        EXTRA_ARGS=""

        if [[ -n '${{ inputs.color }}'  ]]; then
          EXTRA_ARGS="${EXTRA_ARGS} -color=${{ inputs.color }}"
        fi

        if [[ -n '${{ inputs.green }}'  ]]; then
          EXTRA_ARGS="${EXTRA_ARGS} -green=${{ inputs.green }}"
        fi

        if [[ -n '${{ inputs.target }}'  ]]; then
          EXTRA_ARGS="${EXTRA_ARGS} -target=${{ inputs.target }}"
        fi

        if [[ -n '${{ inputs.text }}'  ]]; then
          EXTRA_ARGS="${EXTRA_ARGS} -text=${{ inputs.text }}"
        fi

        if [[ -n '${{ inputs.value }}'  ]]; then
          EXTRA_ARGS="${EXTRA_ARGS} -value=${{ inputs.value }}"
        fi

        if [[ -n '${{ inputs.yellow }}'  ]]; then
          EXTRA_ARGS="${EXTRA_ARGS} -yellow=${{ inputs.yellow }}"
        fi

        if [[ -n '${{ inputs.link }}'  ]]; then
          EXTRA_ARGS="${EXTRA_ARGS} -link=${{ inputs.link }}"
        fi
        
        go install github.com/AlexBeauchemin/gobadge@v0.3.0
        export PATH=$PATH:$(go env GOPATH)/bin
        gobadge -filename=${{ inputs.filename }} $EXTRA_ARGS
      id: coverage-badge-go
      shell: bash

branding:
  icon: check-circle
  color: white
