name: Auto approve

on:
  pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v3
      if: |
        github.actor == 'dependabot[bot]' ||
        github.actor == 'dependabot' ||
        github.actor == 'dependabot-preview[bot]' ||
        github.actor == 'dependabot-preview' ||
        github.actor == 'renovate[bot]' ||
        github.actor == 'renovate'
      with:
        github-token: ${{ secrets.PAT_TOKEN }}
